#!/bin/bash

chown mobile:wheel /Library/Themes
su mobile -c uicache &>/dev/null

echo ""
echo ""
echo "Thank you for installing Paradise 😉"
echo ""
echo "Coded with 🤍"
echo "TitanD3v"
echo ""
echo ""